add_newline = true
palette = "vscode_black"

format = "$directory$git_branch$git_status$fill$cmd_duration$line_break$character"
right_format = "$status$time"

[directory]
style = "bold lavender"
format = "[󰉋  $path]($style) "
truncation_length = 4
truncate_to_repo = false
read_only = " 󰌾"

[git_branch]
symbol = " "
style = "bold mauve"
format = "on [$symbol$branch]($style) "

[git_status]
style = "bold red"
format = "([$all_status$ahead_behind]($style) )"

[cmd_duration]
min_time = 1500
style = "yellow"
format = "[󱎫 $duration]($style) "

[status]
disabled = false
style = "bold red"
format = "[$symbol$status]($style) "

[time]
disabled = false
time_format = "%H:%M"
style = "overlay1"
format = "[ $time]($style)"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold mauve)"

[fill]
symbol = " "

[palettes.vscode_black]
lavender = "#82aaff"
mauve = "#c792ea"
red = "#ff6b6b"
yellow = "#ffd700"
green = "#8bd49c"
overlay1 = "#8b8f96"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
